M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu18.04.1} date Tue 21 Jun 2022 09:58:37 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-21T09:58:37-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu18.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X6.113Y-2.6287
T0
M30
